[2024-06-15T03:45:34.847+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redit_pipeline.s3_upload manual__2024-06-15T03:44:48.144082+00:00 [queued]>
[2024-06-15T03:45:34.861+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redit_pipeline.s3_upload manual__2024-06-15T03:44:48.144082+00:00 [queued]>
[2024-06-15T03:45:34.862+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-06-15T03:45:34.886+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-06-15 03:44:48.144082+00:00
[2024-06-15T03:45:34.913+0000] {standard_task_runner.py:57} INFO - Started process 66 to run task
[2024-06-15T03:45:34.919+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redit_pipeline', 's3_upload', 'manual__2024-06-15T03:44:48.144082+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmplhdc5d2x']
[2024-06-15T03:45:34.932+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask s3_upload
[2024-06-15T03:45:35.045+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_redit_pipeline.s3_upload manual__2024-06-15T03:44:48.144082+00:00 [running]> on host 2121d5985119
[2024-06-15T03:45:35.175+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nithin' AIRFLOW_CTX_DAG_ID='etl_redit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T03:44:48.144082+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-15T03:44:48.144082+00:00'
[2024-06-15T03:45:35.523+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2024-06-15T03:45:35.587+0000] {logging_mixin.py:151} INFO - The file was not found
[2024-06-15T03:45:35.587+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-06-15T03:45:35.613+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_redit_pipeline, task_id=s3_upload, execution_date=20240615T034448, start_date=20240615T034534, end_date=20240615T034535
[2024-06-15T03:45:35.659+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-06-15T03:45:35.692+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
